dataset_root: 'F:\EyeGazeDataset\emotion\fer_2013_data\'
emotion_model_path: 'resources\emotion\'
generate_data_root: 'F:\EyeGazeDataset\emotion\custom_data\'
path_to_csv_dataset: 'F:\EyeGazeDataset\emotion\'